site_name: KT803 KT808 Csv File Description
site_description: KT803 KT808 Csv File Description
site_url: https://hm-info.github.io/ktcsv/

docs_dir: docs

theme:
  name: material
  language: tr
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: blue-grey
      accent: blue-grey

nav:
  - Ana Sayfa / Home: index.md
  - 🇹🇷 Türkçe: turkish.md
  - 🇬🇧 English: english.md

use_directory_urls: false

plugins:
  - search
